services:
  web:
    build: .
    volumes:
      - .:/backend/heartbox
    ports:
      - "8000:8000"
    depends_on:
      - my-postgres
    restart: always
    environment:
      DJANGO_WATCHMAN_TIMEOUT: 20
  my-postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mypassword
    volumes:
      - my_postgres_data:/var/lib/postgresql/data

volumes:
  my_postgres_data:
