from django.urls import path
from . import views

urlpatterns = [
    path("user/sign-in",views.user_login ,name="user_login"),
    path("user/sign-up", views.user_signup, name="user_signup"),
    path("user/logout", views.user_logout, name="user_logout"),
    path("user/check-login", views.check_login, name="check_login"),
    path("user/families",views.family,name="family"),
    path('user/families/join-family', views.join_family, name='join_family'),
    path('user/families/<int:familyId>/', views.family, name='family_by_id'),
    path('user/families/leave-family',views.leave_family,name="leave_family"),
    path('user/families/members',views.getMembersOfFamily,name='family_members'),
    path('user/families/members/<int:familyId>/',views.getMembersOfFamily,name='family_members_by_id'),
    path('user/posts',views.post,name="posts"),
    path('user/posts/<int:familyId>/',views.post,name="family_posts"),
    path('user/posts/category/<str:category>/', views.post, name='posts_by_category'),
    path("user/posts/<int:postId>/", views.post, name="post"),
    path('user/posts/<str:userId>/',views.post,name="user_posts"),
    path('user/posts/<int:post_id>/like', views.like_post, name='like_post'),
    path('user/notifications',views.notification,name='notifications'),
    path("user/notifications/<int:notificationId>/", views.notification, name="notification_detail"),
    path('user/notification/count', views.notification_count, name='notification_count'),
    path('user/notification/<int:notification_id>/read', views.mark_notification_read, name='mark_notification_read'),
    path('user/notification/mark-all-read', views.mark_all_notifications_read, name='mark_all_notifications_read'),
    path('user/users',views.get_user_details,name="user_details_by_id"),
    path('user/connections', views.connections, name="connections"),
    path('connections/request', views.send_connection_request, name='send_connection_request'),
    path('connections/respond', views.respond_to_connection_request, name='respond_to_connection_request'),
    path('connections/cancel', views.cancel_connection_request, name='cancel_connection_request'),
    path('connections/remove', views.remove_connection, name='remove_connection'),
    path('user/comments', views.comments, name='comments'),
]
